### ISSUE TITLE
Duplicate preload stylesheet tags

### ISSUE THREAD

**Issue by nicholaschiang** [joe-bell/next-google-fonts#113]
**Describe the bug**

There are two duplicates of the following preload `<link>` tag:

```html
<link 
  rel="preload" 
  as="style" 
  href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700;800&amp;display=swap"
>
```

**To Reproduce**

1. Go to https://develop.tutorbook.org.
2. Open up devtools inspector.
3. See duplicates.

You can also reproduce locally (see [`components/page/index.tsx`](https://github.com/tutorbookapp/tutorbook/blob/develop/components/page/index.tsx#L150) in [`tutorbookapp/tutorbook`](https://github.com/tutorbookapp/tutorbook)):

1. Follow [these instructions](https://github.com/tutorbookapp/tutorbook#development-environment).
2. Open up http://localhost:3000.
3. See duplicates.

**Expected behavior**

There should only be a single `<link>` tag that is located near the other style tags (instead of being the first tag within the `<head>` element).

**Screenshots**

![double-fonts](https://user-images.githubusercontent.com/20798889/112773686-bca5c880-8feb-11eb-8d51-8fbfc5d9553d.png)

**Desktop (please complete the following information):**

- OS: Pop_OS! 20.04 (Ubuntu 20.04)
- Browser: Firefox 87.0
- Version: 2.1.0

**Comment by joe-bell** [comment]
Hey @nicholaschiang, thanks for the detailed issue!

This is really strange because I'm using the exact same setup as you (`next@10.0.9` and `next-google-fonts@2.1.0` in another project but I can't see this issue at all there. I can see the code you've highlighted in your project, but not in mine.

Just to rule out different approaches, could you try moving the `GoogleFonts` tag into your custom app?
https://github.com/tutorbookapp/tutorbook/blob/develop/pages/_app.tsx#L167

---

After that, please can you try with `next-google-fonts@2.1.1-canary-1` (which I've just published)

This version uses a `key` on head elements, so hopefully we'll be able to detect dupes easier
https://nextjs.org/docs/api-reference/next/head

**Comment by nicholaschiang** [comment]
@joe-bell I think it was actually a bug in the Next.js build cache because:
- I removed the `<GoogleFonts />` component entirely and the first `<link rel='preload' />` tag still existed.
- After I removed the `.next` directory and restarted the development server, the duplicate tags went away.

So it's not a bug here. And I'm not going to file one in Next.js because it's not easily reproducible and was easily fixed.

**Comment by nicholaschiang** [comment]
Actually, nevermind. I can still reproduce this exact same issue using `next-google-fonts@canary` *and* putting the `GoogleFonts` component at the top-level in my custom [`pages/_app.tsx`](https://github.com/nicholaschiang/website/blob/master/pages/_app.tsx).

I've recreated it using [a smaller portfolio website project](https://github.com/nicholaschiang/website) that you should be able to easily use to reproduce this bug:
```
$ git clone https://github.com/nicholaschiang/website && cd website
$ yarn install
$ yarn dev
```

**Comment by joe-bell** [comment]
Sorry @nicholaschiang I'm having trouble running your project locally, if you could provide a minimal hosted example using this setup I'd really appreciate it

I am really baffled by this issue because it's not happening in any of my projects using `next-google-fonts`, I feel like there might be something else at play here that's causing you to see double. I'm hesitant to invest _too_ much time into investigating this if no one else seems to be experiencing the same problem

It looks like this might even be an upstream issue https://github.com/vercel/next.js/issues/9794, https://github.com/vercel/next.js/issues/17085

I'll still add the keys though, I'm not sure why I didn't add them before!

**Comment by nicholaschiang** [comment]
Oh, I think I've got it. It's because I'm using Segment's AJS snippet to add a `<script />` tag that imports the third-party Segment `analytics.min.js` script from their CDN. That messes up the way that Next.js manages our custom tags within `<Head />`.

So it's not an issue with this package but rather with Next.js and my third-party script snippet (that modifies the DOM and adds a `<script />` tag above the first other `<script />` tag). See vercel/next.js#17085 (you were right about that).

I'm going to leave this open for now until that upstream issue is closed (in case any other `next-google-fonts` users experience this as well and, like me, don't think to look in the Next.js issues first).

**Comment by joe-bell** [comment]
Ah thanks for the update, glad you figured it out!

I'm going to close this–I think there's enough context here to lead someone to the relevant upstream issues. We can always revisit if others experience the same issue
